# Generated by Django 4.1.6 on 2023-02-08 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                (
                    "expired_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 2, 11, 7, 37, 45, 476549, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
