# Generated by Django 4.1.6 on 2023-02-08 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="url", old_name="link", new_name="url",),
        migrations.AlterField(
            model_name="url",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 11, 10, 24, 10, 377981, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
