# Generated by Django 4.1.6 on 2023-02-08 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urls", "0002_rename_link_url_url_alter_url_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="expired_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 11, 13, 31, 38, 981265, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
