# Generated by Django 4.1.6 on 2023-02-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense", name="date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="memo",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
