# Generated by Django 4.1.6 on 2023-02-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_expense_date_alter_expense_memo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="books.book",
            ),
        ),
    ]
